BUTTON_NAME = "Название"
BUTTON_PRICE = "Цена"
BUTTON_PRIORITY = "Приоритет"
BUTTON_CONFIRM = "🆗 Подтвердить"
BUTTON_CANCEL = "🔙 Отмена"
BUTTON_BACK = "🔙 Назад"
BUTTON_NEXT = "▶️"
BUTTON_PREV = "◀️"

# EDITION BUTTON
BUTTON_EDIT_NAME = "✏️ Изменить название"
BUTTON_EDIT_PRICE = "💰 Изменить цену"
BUTTON_EDIT_PRIORITY = "⭐ Изменить приоритет"
BUTTON_EDIT_STATUS = "📋 Изменить статус"
BUTTON_EDIT_DESCRIPTION = "📝 Изменить описание"
BUTTON_EDIT_DELETE = "🗑️ Удалить товар"
BUTTON_FILTER_ALL = "Все"
BUTTON_FILTER_ACTIVE = "Не куплены"
BUTTON_FILTER_BOUGHT = "Куплены"